version: "3.8"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/magazine_db
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: magazine_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  